In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,0,0,1]).reshape(-1, 1)

X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sigmoid(z) :
    return 1 / (1 + np.exp(-z))

In [5]:
# initial value of weights
weights = np.random.random((2,1))*2 - 1
weights

array([[0.03382869],
       [0.1179098 ]])

In [6]:
# initial value of bias
bias = np.random.random((1,1))*2 - 1
bias

array([[-0.81052149]])

In [7]:
# Let's do forward propagation
output0 = X   # output of layer 0, i.e. input layer
output1 = sigmoid(np.dot(output0, weights) + bias)

In [8]:
output1

array([[0.30777938],
       [0.33345234],
       [0.3150331 ],
       [0.34101304]])